// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace lab12.Models
{
    public partial class Provider
    {
        public int ProviderId { get; set; }
        public string Name { get; set; }
        public string Telephone { get; set; }
    }
}