// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace lab12.Models
{
    public partial class Tariff
    {
        public int TariffId { get; set; }
        public int? ProviderId { get; set; }
        public int? Speed { get; set; }
        public int? Cost { get; set; }
    }
}